# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: stg
appname: nginx-dep
app: myapp
image:
  repository: devpipeline/ravi
  tag: "28707456883"
replicas: 5