# CICD using GitHub actions
#Sets the name of the workflow. It will show up in GitHub Actions UI as CI.
name: Saravanan-Pipeline

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'myapp/**'
      - 'README.md'

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx (Build)
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/saravana:${{github.run_id}}

  Helm-chat-tag-changes:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' myapp/values.yaml

    - name: Commit and push changes into github
      run: |
        git config --global user.email "devpipelinepulse@gmail.com"
        git config --global user.name "devpipeline1"
        git add myapp/values.yaml
        git commit -m "Update tag in Helm chart"
        git push

